# Generated by Django 5.1 on 2024-11-09 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('userName', models.CharField(max_length=100)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('userProfession', models.CharField(blank=True, max_length=100, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('user_email', models.CharField(blank=True, max_length=100, null=True)),
                ('user_address', models.CharField(blank=True, max_length=100, null=True)),
                ('userFeedback', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
