# Generated by Django 5.1 on 2024-11-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userFeedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
