# Generated by Django 5.1 on 2024-11-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_profile_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='featured_image',
            field=models.ImageField(blank=True, default='profileimg/default.jpg', null=True, upload_to='profileimg/'),
        ),
    ]
