# Generated by Django 5.1 on 2024-09-14 07:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chef',
            fields=[
                ('chefName', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('social_fb', models.CharField(blank=True, max_length=100, null=True)),
                ('social_x', models.CharField(blank=True, max_length=100, null=True)),
                ('social_ld', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
