# Generated by Django 5.1 on 2024-09-18 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_chef_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='iceCream',
            fields=[
                ('iCream_price', models.IntegerField()),
                ('iCream_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('iCream_name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
