# Generated by Django 5.1 on 2024-11-09 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_icecream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('Service_name', models.CharField(max_length=100)),
                ('Service_description', models.TextField(blank=True, null=True)),
                ('Service_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
