# Generated by Django 5.1 on 2024-11-30 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_query', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
